# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^tests/data/
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: detect-private-key
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    -   id: codespell
-   repo: https://github.com/MarcoGorelli/auto-walrus
    rev: v0.2.1
    hooks:
    -   id: auto-walrus
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore
    -   id: rst-inline-touching-normal
    -   id: rst-directive-colons
    -   id: rst-backticks
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
-   repo: local
    hooks:
    -   id: dontship
        name: Do not commit "DO NOT SUBMIT"
        entry: DO\sNOT\SUBMIT
        language: pygrep
        types: [text]
